

import './globals.css'
import Navbar from '../components/navbar'
import { Inter } from 'next/font/google'
import Footer from '../components/footer'
import { Provider } from 'react-redux'
import {store }from '@/store/store'

const inter = Inter({ subsets: ['latin'] })
export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className=''>
      {/* <Provider store={store}> */}

      <body className={`${inter.className}`}>{children}
      
      
      </body>
      {/* </Provider> */}
      
    </html>
  )
}
