

import './globals.css'
import Navbar from '../components/navbar'

import Footer from '../components/footer'




export const dynamic = 'force-dynamic'

export const metadata = {
  title: 'Dine Market',
  description: 'Generated by Dine Market',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en" className=''>
      

      <body>
      <Navbar />
        {children}
        <Footer />
      </body>
      
      
    </html>
    
  )
}
